apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: internal-tools
  labels:
    app: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
        - name: admin-panel
          image: ctf/admin-panel:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FLAG_F7
              value: "FLAG{ssrf_1nt0_th3_1nt3rn4l_n3t}"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
