apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: saas-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-log
  namespace: escape-zone
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-pod-exec-log
  namespace: escape-zone
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: saas-app
roleRef:
  kind: Role
  name: pod-exec-log
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-cluster-reader
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: saas-app
  - kind: ServiceAccount
    name: backend-sa
    namespace: internal-tools
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
