# Generated by Django 5.2.17 on 2026-08-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=140)),
                ('squad', models.CharField(max_length=120)),
                ('member_username', models.CharField(max_length=80)),
                ('dashboard_note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True, default='')),
                ('visible_in_frontend', models.BooleanField(default=True)),
                ('staff_only', models.BooleanField(default=False)),
                ('handoff_note', models.TextField(blank=True, default='')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='vault.queue')),
            ],
        ),
    ]
