apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: saas-app
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: saas-app-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ctf.localhost
      secretName: ctf-tls
  rules:
    - host: ctf.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
