from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="part1_index"),
    path("sql/safe/", views.sql_safe, name="sql_safe"),
    path("sql/vulnerable/", views.sql_vulnerable, name="sql_vulnerable"),
    path("sql/fixed/", views.sql_fixed, name="sql_fixed"),
    path("xss/upload/", views.xss_upload, name="xss_upload"),
    path("xss/safe/", views.xss_safe, name="xss_safe"),
    path("xss/vulnerable/", views.xss_vulnerable, name="xss_vulnerable"),
    path("xss/fixed/", views.xss_fixed, name="xss_fixed"),
    path("xss/preview/", views.xss_preview_vulnerable, name="xss_preview_vulnerable"),
    path("xss/preview/fixed/", views.xss_preview_fixed, name="xss_preview_fixed"),
    path("csrf/safe/", views.csrf_safe, name="csrf_safe"),
    path("csrf/vulnerable/", views.csrf_vulnerable, name="csrf_vulnerable"),
    path("csrf/fixed/", views.csrf_fixed, name="csrf_fixed"),
    path("csrf/attack-page/", views.csrf_attack_page, name="csrf_attack_page"),
    path("clickjacking/protected/", views.clickjacking_protected, name="clickjacking_protected"),
    path("redirect/vulnerable/", views.redirect_vulnerable, name="redirect_vulnerable"),
    path("redirect/fixed/", views.redirect_fixed, name="redirect_fixed"),
    path("idor/reference/", views.idor_reference, name="idor_reference"),
    path("integration/", views.part2_index, name="part2_index"),
    path("files/vulnerable/", views.file_vulnerable, name="file_vulnerable"),
    path("files/fixed/", views.file_fixed, name="file_fixed"),
    path("subprocess/vulnerable/", views.subprocess_vulnerable, name="subprocess_vulnerable"),
    path("subprocess/blind/", views.subprocess_blind, name="subprocess_blind"),
    path("subprocess/fixed/", views.subprocess_fixed, name="subprocess_fixed"),
    path("fetch/vulnerable/", views.fetch_vulnerable, name="fetch_vulnerable"),
    path("fetch/fixed/", views.fetch_fixed, name="fetch_fixed"),
    path("fetch/public-api/", views.public_api, name="public_api"),
    path("fetch/internal-admin/", views.internal_admin, name="internal_admin"),
    path("webhooks/attacker-sink/", views.attacker_sink, name="attacker_sink"),
    path("webhooks/events/", views.attacker_events, name="attacker_events"),
    path("tasks/vulnerable/", views.task_vulnerable, name="task_vulnerable"),
    path("tasks/fixed/", views.task_fixed, name="task_fixed"),
    path("privileged/vulnerable/", views.privileged_vulnerable, name="privileged_vulnerable"),
    path("privileged/fixed/", views.privileged_fixed, name="privileged_fixed"),
]
